version: '2.2'
services:
  rctf:
    build: .
    restart: always
    ports:
      - "8080:80"
    expose:
      - "80"
    networks:
      - internal
    env_file:
      - .env
    environment:
      - PORT=80
    volumes:
      - ./conf.d:/app/conf.d
    depends_on:
      - redis
      - postgres
  redis:
    image: redis:6
    restart: always
    command: ["redis-server", "--requirepass", "${RCTF_REDIS_PASSWORD}"]
    networks:
      - internal
    volumes:
      - ./data/rctf-redis:/data
  postgres:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_PASSWORD=${RCTF_DATABASE_PASSWORD}
      - POSTGRES_USER=rctf
      - POSTGRES_DB=rctf
    networks:
      - internal
    volumes:
      - ./data/rctf-postgres:/var/lib/postgresql/data

networks:
  internal: {}
